### ISSUE TITLE
Getting GH Token Error

### ISSUE THREAD

**Issue by ghost** [Dogey11/B3#11]
Hi, great code/program. Ever since new update you did though i'm getting the following error now when trying to set up. Is there any thing you'd recommend to fix? Also, where would I add the token I tried generating one on Github but still didn't work  when I added it to the code. Thanks!!!

ValueError(f"API Rate limit exceeded. You have to add GH_TOKEN!!!")
ValueError: API Rate limit exceeded. You have to add GH_TOKEN!!!

**Comment by 1404er** [comment]
Hi,

I was unable to reproduce the error, but [from my understanding](https://github.com/SergeyPirogov/webdriver_manager#gh_token) of it, the bug should now be fixed [with this new version](https://github.com/Dogey11/B3/releases/tag/v2.0.0). The code isn't the most stable but it's nice to hear someone found it useful.

This new version also has a different installation process which you can read [here](https://github.com/Dogey11/B3/blob/main/docs/GETTING_STARTED.md).
