### ISSUE TITLE
No CVV User Input field - Selenium/webdriver to Playwright?

### ISSUE THREAD

**Issue by ghost** [Dogey11/B3#15]
So sorry man please don't hate me but one more question/concern. Realized that the older versions of this had a user input to insert the CVV code, but this new one with playwright doesn't. I'm assuming that's on purpose? I tried to look at the older version and copy paste the code but realized that one was using selenium and bunch of other dependencies and this one's using playwright so i kind of got stuck. Sorry man! Beautiful work regardless haha keep it up!

**Comment by 1404er** [comment]
haha its ok. The reason there is no CVV prompt is because when I ran it, it seems the store no longer asks for it at checkout, as long as you have the card saved. If it's different for you please let me know

**Comment by ghost** [comment]
It is different for me unfortunately, the verification phase stops at the CVV enter field on the webpage waiting to be inserted, then closes and says "verification complete"

**Comment by 1404er** [comment]
Unfortunately, it seems Best Buy's latest site update now requires entering full card info and shipping address, meaning the bot can no longer rely on default account info and it does not function properly unless this changes in the future. Until that happens, it seems there is nothing I can do.
