### ISSUE TITLE
BB Link needs to be hardcoded

### ISSUE THREAD

**Issue by dualaudi** [Dogey11/B3#2]
The script asks for the link, email/pw/cvv - but you have the link hardcoded regardless - so just needs to be edited in main.py. Script works fine as of now after I edited the file.

**Comment by 1404er** [comment]
could you give an example of what you mean?

Edit: I don't see a way to hardcode the link if it can vary.

**Comment by dualaudi** [comment]
![Screenshot 2021-12-27 223437-bb-link](https://user-images.githubusercontent.com/17436208/147535812-07d7f9bb-9be0-4377-a623-79ffa115c122.png)
Your script is asking for the link in step1 before it asks for email/pw/cvv.. - Doesn't matter what I paste, it's hardcoded on line 41. I think you have it defaulted to nintendo $5 card in your downloaded files. I tried (LINK) but that didn't work for me. 

So I just manually replaced your gift card link on line 41 for the product I want to buy. I'm running 3 of your bots for 3 different cards, waiting for BB to restock.

**Comment by 1404er** [comment]
> ![Screenshot 2021-12-27 223437-bb-link](https://user-images.githubusercontent.com/17436208/147535812-07d7f9bb-9be0-4377-a623-79ffa115c122.png) Your script is asking for the link in step1 before it asks for email/pw/cvv.. - Doesn't matter what I paste, it's hardcoded on line 41. I think you have it defaulted to nintendo $5 card in your downloaded files. I tried (LINK) but that didn't work for me.
> 
> So I just manually replaced your gift card link on line 41 for the product I want to buy. I'm running 3 of your bots for 3 different cards, waiting for BB to restock.

oh I see now, that wasn't supposed to be there lol

ive updated it and the link prompt should work as intended.
