### ISSUE TITLE
Selenium not clicking "Place Order" Element

### ISSUE THREAD

**Issue by ghost** [Dogey11/B3#3]
Hi so I ran this code and everything works perfectly just until the order is about to be placed. The item gets added to my cart and it logs me in but the driver does not click place order for me. I took a look at the code and I'm assuming something has to be going on here ? 

confirmBuy = driver.find_element(By.CLASS_NAME, "btn-lg.btn-block.btn-primary.button__fast-track")
            confirmBuy.click()

I looked at the elements on chrome and the element you have is correct but maybe it should not find element by class? And have it find by XPATH? What do you think? Do you have any solution to this? Thanks so much!

**Comment by 1404er** [comment]
Hi,

Just to clarify,
Does this happen during running verify..py or running the actual program? verify.py is set to not press buy while main.py is

**Comment by 1404er** [comment]
I've tested it again myself and I think I found the issue.

I've just released version 0.4. It should have this fixed along with other bugs. I'd recommend deleting the b3v0.3win.zip folder & deleting the C:\b3 directory. Chromedriver is also no longer needed with this update.

**Comment by ghost** [comment]
> Hi,
> 
> Just to clarify, Does this happen during running verify..py or running the actual program? verify.py is set to not press buy while main.py is

Hi, it was happening while running the actual program! verify.py would just make google chrome crash but the actual program didn't, worrked fine other than not clicking the place order button.

And great! Thanks so much i'll give it a shot right now.
